default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  password: 123456
  port: 5432

development:
  primary: &primary_development
    <<: *default
    database: cideclasse_development
  queue:
    <<: *primary_development
    database: cideclasse_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: cideclasse_test

production:
  primary: &primary_production
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    database: cideclasse_production_queue
    username: <%= ENV["DB_USER"] %>
    host: <%= ENV["DB_HOST"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    port: <%= ENV["DB_PORT"] %>
    migrations_paths: db/queue_migrate
